
export const TIME_SLOTS = [
  "08:00 AM - 10:00 AM",
  "10:00 AM - 12:00 PM",
  "12:00 PM - 02:00 PM",
  "02:00 PM - 04:00 PM",
  "04:00 PM - 06:00 PM",
  "06:00 PM - 08:00 PM"
];

export const TRANSLATIONS = {
  EN: {
    dashboard: "Dashboard",
    jobs: "Jobs",
    drivers: "Drivers",
    supervisors: "Supervisors",
    vehicles: "Vehicles",
    users: "Users",
    logs: "Activity Logs",
    logout: "Logout",
    createJob: "Create Job",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Completed",
    history: "History",
    priority: "Priority",
    purpose: "Purpose",
    date: "Date",
    time: "Time Slot",
    actions: "Actions",
    assign: "Assign",
    remarks: "Remarks",
    status: "Status",
    low: "Low",
    medium: "Medium",
    high: "High",
    madeBy: "Made by Harsh Bansal",
    welcome: "Welcome back",
    stats: "Dashboard Statistics",
    activeDrivers: "Active Drivers",
    pendingJobs: "Pending Jobs",
    approvedJobs: "Approved Jobs",
    completedJobs: "Completed Jobs",
    printSlip: "Print Job Slip",
    updateProgress: "Update Progress",
    reached: "Reached",
    onWork: "On Work",
    acceptJob: "Accept Job",
    driverStatus: "Driver Status",
    vehicleStatus: "Vehicle Status",
    add: "Add",
    delete: "Delete",
    confirm: "Confirm",
    cancel: "Cancel",
    available: "Available",
    onLeave: "On Leave",
    active: "Active",
    maintenance: "Maintenance",
    outOfService: "Out of Service",
    loginTitle: "TransLogix Login",
    username: "Username",
    password: "Password",
    login: "Sign In",
    search: "Search...",
    addUser: "Add New User",
    role: "Role",
    name: "Name",
    themeToggle: "Toggle Dark Mode",
    jobBoard: "Job Board",
    myJobs: "My Jobs",
    apply: "Apply for Job",
    claimed: "Claimed By You",
    fromPlace: "From Place",
    toPlace: "To Place",
    addSupervisor: "Add Supervisor"
  },
  HI: {
    dashboard: "डैशबोर्ड",
    jobs: "कार्य",
    drivers: "ड्राइवर",
    supervisors: "सुपरवाइजर",
    vehicles: "वाहन",
    users: "उपयोगकर्ता",
    logs: "गतिविधि लॉग",
    logout: "लॉगआउट",
    createJob: "कार्य बनाएं",
    pending: "लंबित",
    approved: "अनुमोदित",
    rejected: "अस्वीकृत",
    completed: "पूर्ण",
    history: "इतिहास",
    priority: "प्राथमिकता",
    purpose: "उद्देश्य",
    date: "तारीख",
    time: "समय स्लॉट",
    actions: "कार्रवाई",
    assign: "सौंपें",
    remarks: "टिप्पणियाँ",
    status: "स्थिति",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    madeBy: "हर्ष बंसल द्वारा निर्मित",
    welcome: "स्वागत है",
    stats: "डैशबोर्ड सांख्यिकी",
    activeDrivers: "सक्रिय ड्राइवर",
    pendingJobs: "लंबित कार्य",
    approvedJobs: "अनुमोदित कार्य",
    completedJobs: "पूर्ण कार्य",
    printSlip: "स्लिप प्रिंट करें",
    updateProgress: "प्रगति अपडेट करें",
    reached: "पहुँच गए",
    onWork: "काम पर",
    acceptJob: "कार्य स्वीकार करें",
    driverStatus: "ड्राइवर की स्थिति",
    vehicleStatus: "वाहन की स्थिति",
    add: "जोड़ें",
    delete: "हटाएं",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    available: "उपलब्ध",
    onLeave: "छुट्टी पर",
    active: "सक्रिय",
    maintenance: "रखरखाव",
    outOfService: "सेवा से बाहर",
    loginTitle: "ट्रांसलॉजिक्स लॉगिन",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    login: "साइन इन करें",
    search: "खोजें...",
    addUser: "नया उपयोगकर्ता जोड़ें",
    role: "भूमिका",
    name: "नाम",
    themeToggle: "डार्क मोड टॉगल करें",
    jobBoard: "कार्य बोर्ड",
    myJobs: "मेरे कार्य",
    apply: "कार्य के लिए आवेदन करें",
    claimed: "आपके द्वारा दावा किया गया",
    fromPlace: "कहाँ से",
    toPlace: "कहाँ तक",
    addSupervisor: "सुपरवाइजर जोड़ें"
  }
};
